# Generated by Django 3.0.3 on 2020-02-20 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tboard', '0002_auto_20200220_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timery',
            name='timer',
        ),
        migrations.RemoveField(
            model_name='timery',
            name='timer1',
        ),
    ]
