# Generated by Django 3.0.3 on 2020-02-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tboard', '0003_auto_20200220_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='timery',
            name='date1',
            field=models.TextField(blank=True),
        ),
    ]
